import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const Message = ({ message, onFeedback, showContextIndicator = true }) => {
    const [showMetadata, setShowMetadata] = useState(false);
    const [showSources, setShowSources] = useState(false);
    const [copySuccess, setCopySuccess] = useState(false);

    // 🔊 NEW: Track speaking state
    const [isSpeaking, setIsSpeaking] = useState(false);

    const isUser = message.sender === 'user';
    const isError = message.isError || false;

    const formatTimestamp = (timestamp) => {
        if (timestamp instanceof Date) {
            return timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        }
        return new Date(timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };

    // 🔊 NEW: Multi-language voice support
    const speakText = (text) => {
        if (!text) return;

        // If already speaking → STOP
        if (isSpeaking) {
            window.speechSynthesis.cancel();
            setIsSpeaking(false);
            return;
        }

        // Choose correct voice
        const utter = new SpeechSynthesisUtterance(text);
        utter.rate = 0.95;
        utter.pitch = 1;

        const indianLangs = [
            "hi", "bn", "ta", "te", "mr", "gu", "pa", "kn", "ml", "or"
        ];

        let detectedLang = "en-IN";

        // naive detection based on unicode range
        if (/[\u0900-\u097F]/.test(text)) detectedLang = "hi-IN"; // Hindi
        if (/[\u0B80-\u0BFF]/.test(text)) detectedLang = "ta-IN"; // Tamil
        if (/[\u0C00-\u0C7F]/.test(text)) detectedLang = "te-IN"; // Telugu
        if (/[\u0980-\u09FF]/.test(text)) detectedLang = "bn-IN"; // Bengali
        if (/[\u0D80-\u0DFF]/.test(text)) detectedLang = "ml-IN"; // Malayalam

        utter.lang = detectedLang;

        // When speaking ends → reset button
        utter.onend = () => setIsSpeaking(false);

        window.speechSynthesis.cancel();
        window.speechSynthesis.speak(utter);
        setIsSpeaking(true);
    };

    const cleanResponseText = (text) => {
        if (!text) return text;
        const parts = text.split('---');
        if (parts.length > 1) return parts[0].trim();
        const sourcesIndex = text.toLowerCase().indexOf('sources:');
        if (sourcesIndex > -1) return text.substring(0, sourcesIndex).trim();
        const responseGenIndex = text.toLowerCase().indexOf('response generated by');
        if (responseGenIndex > -1) return text.substring(0, responseGenIndex).trim();
        return text;
    };

    const copyToClipboard = async (text) => {
        try {
            await navigator.clipboard.writeText(text);
            setCopySuccess(true);
            setTimeout(() => setCopySuccess(false), 2000);
        } catch (err) {
            console.error('Failed to copy text: ', err);
        }
    };

    const downloadResponse = () => {
        const data = {
            message: message.text,
            timestamp: message.timestamp,
            sources: message.sources || [],
            metadata: {
                hasContext: message.hasContext,
                generationTime: message.generationTime,
                feedback: message.feedback
            }
        };
        
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `HealthChatPal-response-${Date.now()}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const getMessageWidth = () => {
        const textLength = message.text.length;
        if (textLength < 100) return 'max-w-[70%] sm:max-w-[60%]';
        if (textLength < 300) return 'max-w-[85%] sm:max-w-[75%]';
        return 'max-w-[95%] sm:max-w-[85%]';
    };

    return (
        <div className={`flex ${isUser ? 'justify-end' : 'justify-start'} mb-4 sm:mb-6`}>
            <div className={`flex items-start space-x-2 sm:space-x-3 ${getMessageWidth()} ${isUser ? 'flex-row-reverse space-x-reverse' : ''}`}>

                {/* Avatar */}
                <div className={`w-7 h-7 sm:w-9 sm:h-9 rounded-full flex items-center justify-center flex-shrink-0 shadow-sm ${
                    isUser 
                        ? 'bg-gradient-to-r from-blue-600 to-blue-700' 
                        : isError 
                        ? 'bg-gradient-to-r from-red-500 to-red-600'
                        : 'bg-gradient-to-r from-green-500 to-green-600'
                }`}>
                    <span className="text-white text-xs sm:text-sm font-medium">
                        {isUser ? 'Y' : isError ? '⚠️' : '🏥'}
                    </span>
                </div>

                {/* Message Bubble */}
                <div className="flex-1 min-w-0">

                    {!isUser && message.hasContext && showContextIndicator && (
                        <div className="flex items-center space-x-2 mb-2">
                            <div className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse"></div>
                            <span className="text-xs font-medium text-green-600 bg-green-50 px-2 py-1 rounded-full">
                                Following up on our conversation
                            </span>
                        </div>
                    )}

                    <div className={`relative px-3 py-2 sm:px-4 sm:py-3 rounded-2xl shadow-sm ${
                        isUser
                            ? 'bg-blue-600 text-white rounded-tr-sm'
                            : isError
                            ? 'bg-red-50 text-red-800 border border-red-200 rounded-tl-sm'
                            : 'bg-white text-gray-800 border border-gray-200 rounded-tl-sm'
                    }`}>

                        {/* Bot message markdown */}
                        {!isUser ? (
                            <div className="prose prose-sm sm:prose-base max-w-none text-gray-800">
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                    {cleanResponseText(message.text)}
                                </ReactMarkdown>
                            </div>
                        ) : (
                            <p className="text-sm sm:text-base leading-relaxed whitespace-pre-wrap font-medium">
                                {message.text}
                            </p>
                        )}

                        {/* 🔊 NEW: SPEAK BUTTON */}
                        {!isUser && !isError && (
                            <button
                                onClick={() => speakText(cleanResponseText(message.text))}
                                className="mt-3 flex items-center space-x-1 px-2 py-1 text-xs text-gray-700 hover:text-gray-900 bg-gray-100 hover:bg-gray-200 rounded-md transition"
                            >
                                <span>{isSpeaking ? "🔇 Stop" : "🔊 Listen"}</span>
                            </button>
                        )}

                        {/* Existing buttons (copy/download/etc) */}
                        {/* (unchanged code continues...) */}
                    </div>

                    <div className={`text-xs text-gray-400 mt-2 ${isUser ? 'text-right' : 'text-left'}`}>
                        {formatTimestamp(message.timestamp)}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Message;
